name: k_debug_tools
description: KDebugTools is a powerful library for debugging Flutter applications.
version: 1.0.2
homepage: https://github.com/KwaiAppTeam/KDebugTools
level: utility
publish_to: 'https://pub.dev'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^2.0.0
  device_info: ^0.4.2+4
  shared_preferences: ^0.5.7+3
  package_info: '>=0.4.0+16 <2.0.0'
  #web服务
  http_server: ^0.9.8+3
  http_multi_server: ^2.2.0
  web_socket_channel: ^1.2.0
  stream_channel: ^2.0.0
  convert: ^2.0.2
  crypto: ^2.0.0
  http_parser: ^3.1.0
  path: ^1.7.0
  intl: ^0.16.0
  mime: ^0.9.7
  shelf: ^0.7.9
  shelf_static: ^0.2.8
  shelf_router: ^0.7.2
  shelf_web_socket: ^0.2.3
  #静态资源代理到cdn上减少包体积
  shelf_proxy: ^0.1.0+7
  #uri工具集用于uri匹配
  uri: ^0.11.3+1
  #读文件
  path_provider: ^1.6.14
  #压缩文件
  archive: ^2.0.13
  #toast
  oktoast: ^2.3.2
  #数据库
  sqflite: ^1.3.1
  wifi_info_flutter: ^1.0.3
  photo_manager: ^0.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.kwai.flutter.debugtools
        #todo 临时用这个 整理后挪走
        pluginClass: ScreenPreviewPlugin
      ios:
        pluginClass: DebugtoolsPlugin
