name: k_debug_tools
description: KDebugTools is a powerful library for debugging Flutter applications.
version: 2.0.0-nullsafety.2
homepage: https://github.com/KwaiAppTeam/KDebugTools
level: utility
publish_to: 'https://pub.dev'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.0
  device_info: ^2.0.0
  shared_preferences: ^2.0.0
  package_info: ^2.0.0
  #web服务
  http_server: ^1.0.0
  http_multi_server: ^3.0.0
  web_socket_channel: ^2.0.0
  stream_channel: ^2.1.0
  convert: ^3.0.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  path: ^1.8.0
  intl: ^0.17.0
  mime: ^1.0.0
  shelf: ^1.0.0
  shelf_static: ^1.0.0
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.0
  #静态资源代理到cdn上减少包体积
  shelf_proxy: ^1.0.0
  #uri工具集用于uri匹配
  uri: ^1.0.0
  #读文件
  path_provider: ^2.0.0
  #压缩文件
  archive: ^3.1.1
  #toast
  oktoast: ^3.0.0
  #数据库
  sqflite: ^2.0.0+3
  wifi_info_flutter: ^2.0.0
  photo_manager: ^1.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.kwai.flutter.debugtools
        #todo 临时用这个 整理后挪走
        pluginClass: ScreenPreviewPlugin
      ios:
        pluginClass: DebugtoolsPlugin
