name: k_debug_tools_web
description: Web tools for KDebugTools.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^3.0.4
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  oktoast: ^3.0.0
  intl: ^0.17.0
  rxdart: ^0.26.0
  web_socket_channel: ^2.0.0
  event_bus: ^2.0.0
  cached_network_image: ^3.0.0
  #video player
  chewie: ^1.0.0
  video_player: ^2.1.1
  video_player_web: ^2.0.0
  pin_code_fields: ^7.0.0
  shared_preferences: ^2.0.5
  shared_preferences_web: ^2.0.0
  visibility_detector: ^0.2.0
  provider: ^5.0.0
  firebase_analytics: ^7.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true